version: '3.8'

services:
  ziltek:
    container_name: ziltek
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3014:3014
    environment:
      - PORT=3014
    command: pnpm run run
