name: Build & Publish

on:
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            args: ""
          - platform: ubuntu-20.04
            args: ""
          - platform: windows-latest
            args: "--target i686-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.11.0

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install toolchain (win)
        if: matrix.args != '' && matrix.platform == 'windows-latest'
        run: rustup target add i686-pc-windows-msvc

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GH }}
          TAURI_PRIVATE_KEY: ${{ secrets.KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        with:
          tagName: ZilTek-v__VERSION__
          releaseName: "ZilTek v__VERSION__"
          releaseBody: "evet"
          releaseDraft: true
          prerelease: true
          includeUpdaterJson: true
          releaseCommitish: "main"
          owner: "TheAlan404"
          repo: "ZilTekProject"
