name: Build

on:
  push: 
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Vite Build
        run: pnpm build
      
      - uses: actions/upload-artifact@v4
        with:
          name: ziltek-source
          path: dist
