name: push to docker.kuylar.dev

on:
  workflow_dispatch:

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install frontend dependencies
        run: npm install

      - name: build frontend
        run: npm run build --mode web

      # todo
